{
  "id": "CVE-2018-20430",
  "assigner": "cve@mitre.org",
  "last_modified": "2019-01-11T19:07:51.300",
  "vulnerable_configuration": [
    "cpe:2.3:a:gnu:libextractor:0.5.9:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.5.20c:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.5.21:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.5.22:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.5.23:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.6.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.6.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.6.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:0.6.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.0.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.0.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.6:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.7:*:*:*:*:*:*:*",
    "cpe:2.3:a:gnu:libextractor:1.8:*:*:*:*:*:*:*",
    "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
    "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*"
  ],
  "cwe": "en",
  "summary": "GNU Libextractor through 1.8 has an out-of-bounds read vulnerability in the function history_extract() in plugins/ole2_extractor.c, related to EXTRACTOR_common_convert_to_utf8 in common/convert.c.",
  "references": [
    "http://www.securityfocus.com/bid/106300",
    "https://gnunet.org/bugs/view.php?id=5493",
    "https://gnunet.org/git/libextractor.git/commit/?id=b405d707b36e0654900cba78e89f49779efea110",
    "https://gnunet.org/git/libextractor.git/tree/ChangeLog",
    "https://lists.debian.org/debian-lts-announce/2018/12/msg00015.html",
    "https://www.debian.org/security/2018/dsa-4361"
  ]
}